### ISSUE TITLE
Sound Driver master todo list

### ISSUE THREAD

**Issue by freem** [freem/freemlib-neogeo#2]
The Sound Driver is a combination of multiple components:
- [X] Required hardware calls/routines (`$01` = slot switch, `$03` = soft reset, writing `1` to port `0xC0`, etc.)
- [ ] ADPCM-A sample playback (#3)
- [ ] ADPCM-B sample playback (#4)
- [ ] FM channel playback (#5)
- [ ] SSG channel playback (#6)
- [ ] CD-DA playback (#7)
- [ ] Frequency tables (FM, SSG)
- [ ] Music/sound effect sequence playback (#8)
- [ ] Various commands (#9)
- [ ] Memory banking and manipulation (#10)
